/* cogs/verification/presets.js — one-click configs */

module.exports = [
  {
    id: 'chill',
    label: 'chill',
    desc: 'one-click verify, no gates. trusted servers only.',
    config: {
      methods: ['button'],
      methodPrimary: 'button',
      ageGateEnabled: false,
      altThreshold: 999,
      antiraidEnabled: false,
      failAction: 'none',
      captchaMaxAttempts: 99,
      rememberDays: 30,
    },
  },
  {
    id: 'standard',
    label: 'standard',
    desc: 'button + captcha, age gate on. good for most servers.',
    config: {
      methods: ['button', 'captcha'],
      methodPrimary: 'captcha',
      ageGateEnabled: true,
      ageGateDays: 7,
      ageGateAction: 'captcha',
      altThreshold: 4,
      antiraidEnabled: true,
      antiraidThreshold: 15,
      antiraidWindowSeconds: 60,
      antiraidForceCaptcha: true,
      failAction: 'quarantine',
      captchaMaxAttempts: 3,
      rememberDays: 7,
    },
  },
  {
    id: 'serious',
    label: 'serious',
    desc: 'image captcha + rules quiz. kills bots and alts.',
    config: {
      methods: ['captcha', 'quiz'],
      methodPrimary: 'captcha',
      ageGateEnabled: true,
      ageGateDays: 14,
      ageGateAction: 'captcha',
      altThreshold: 3,
      antiraidEnabled: true,
      antiraidThreshold: 10,
      antiraidWindowSeconds: 60,
      antiraidForceCaptcha: true,
      failAction: 'quarantine',
      captchaMaxAttempts: 3,
      rememberDays: 7,
    },
  },
  {
    id: 'paranoid',
    label: 'paranoid',
    desc: 'dm code + manual review fallback. max security.',
    config: {
      methods: ['dmcode', 'manual'],
      methodPrimary: 'dmcode',
      ageGateEnabled: true,
      ageGateDays: 30,
      ageGateAction: 'dmcode',
      altThreshold: 2,
      antiraidEnabled: true,
      antiraidThreshold: 5,
      antiraidWindowSeconds: 60,
      antiraidForceCaptcha: true,
      failAction: 'manual',
      captchaMaxAttempts: 1,
      rememberDays: 3,
    },
  },
];
